package model;

import java.util.Arrays;
import java.util.List;

public class SupportedCoins {

    public static List<String> getCurrencyCode() {
        return currencyCode;
    }
    public static List<String> getPortugueseCoins() {
        return portugueseCoins;
    }
    public static List<String> getEnglishcoins() {
        return Englishcoins;
    }
    public static String[] getCountry() {
        return country;
    }

    private static List<String> currencyCode = Arrays.asList(
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHF",
            "CLP",
            "CNY",
            "COP",
            "CRC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "FJD",
            "FKP",
            "FOK",
            "GBP",
            "GEL",
            "GGP",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "IMP",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JEP",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KID",
            "KMF",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TVD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "UYU",
            "UZS",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAF",
            "XCD",
            "XDR",
            "XOF",
            "XPF",
            "YER",
            "ZAR",
            "ZMW",
            "ZWL"
    );



    private static List<String> Englishcoins = Arrays.asList(
             "UAE Dirham",
             "Afghan Afghani",
             "Albanian Lek",
             "Armenian Dram",
             "Netherlands Antillian Guilder",
             "Angolan Kwanza",
             "Argentine Peso",
             "Australian Dollar",
             "Aruban Florin",
             "Azerbaijani Manat",
             "Bosnia and Herzegovina Mark",
             "Barbados Dollar",
             "Bangladeshi Taka",
             "Bulgarian Lev",
             "Bahraini Dinar",
             "Burundian Franc",
             "Bermudian Dollar",
             "Brunei Dollar",
             "Bolivian Boliviano",
             "Brazilian Real",
             "Bahamian Dollar",
             "Bhutanese Ngultrum",
             "Botswana Pula",
             "Belarusian Ruble",
             "Belize Dollar",
             "Canadian Dollar",
             "Congolese Franc Democratic",
             "Swiss Franc",
             "Chilean Peso",
             "Chinese Renminbi",
             "Colombian Peso",
             "Costa Rican",
             "Cuban Peso",
             "Cape Verdean",
             "Czech Koruna",
             "Djiboutian Franc",
             "Danish Krone",
             "Dominican Peso",
             "Algerian Dinar",
             "Egyptian Pound",
             "Eritrean Nakfa",
             "Ethiopian Birr",
             "Euro",
             "Fiji Dollar",
             "Falkland Islands Pound",
             "Faroese Króna",
             "Pound Sterling",
             "Georgian Lari",
             "Guernsey Pound",
             "Ghanaian Cedi",
             "Gibraltar Pound",
             "Gambian Dalasi",
             "Guinean Franc",
             "Guatemalan Quetzal",
             "Guyanese Dollar",
             "Hong Kong Dollar",
             "Honduran Lempira",
             "Croatian Kuna",
             "Haitian Gourde",
             "Hungarian Forint",
             "Indonesian Rupiah",
             "Israeli New Shekel",
             "Manx Pound",
             "Indian Rupee",
             "Iraqi Dinar",
             "Iranian Rial",
             "Icelandic Króna",
             "Jersey Pound",
             "Jamaican Dollar",
             "Jordanian Dinar",
             "Japanese Yen",
             "Kenyan Shilling",
             "Kyrgyzstani Som",
             "Cambodian Riel",
             "Kiribati Dollar",
             "Comorian Franc",
             "South Korean Won",
             "Kuwaiti Dinar",
             "Cayman Islands Dollar",
             "Kazakhstani Tenge",
             "Lao Kip",
             "Lebanese Pound",
             "Sri Lanka Rupee",
             "Liberian Dollar",
             "Lesotho Loti",
             "Libyan Dinar",
             "Moroccan Dirham",
             "Moldovan Leu",
             "Malagasy Ariary",
             "Macedonian Denar",
             "Burmese Kyat",
             "Mongolian Tögrög",
             "Macanese Pataca",
             "Mauritanian Ouguiya",
             "Mauritian Rupee",
             "Maldivian Rufiyaa",
             "Malawian Kwacha",
             "Mexican Peso",
             "Malaysian Ringgit",
             "Mozambican Metical",
             "Namibian Dollar",
             "Nigerian Naira",
             "Nicaraguan Córdoba",
             "Norwegian Krone",
             "Nepalese Rupee",
             "New Zealand Dollar",
             "Omani Rial",
             "Panamanian Balboa",
             "Peruvian Sol",
             "Papua New Guinean Kina",
             "Philippine Peso",
             "Pakistani Rupee",
             "Polish Złoty",
             "Paraguayan Guaraní",
             "Qatari Riyal",
             "Romanian Leu",
             "Serbian Dinar",
             "Russian Ruble",
             "Rwandan Franc",
             "Saudi Riyal",
             "Solomon Islands Dollar",
             "Seychellois Rupee",
             "Sudanese Pound",
             "Swedish Krona",
             "Singapore Dollar",
             "Saint Helena Pound",
             "Sierra Leonean Leone",
             "Somali Shilling",
             "Surinamese Dollar",
             "South Sudanese Pound",
             "São Tomé and Príncipe Dobra",
             "Syrian Pound",
             "Eswatini Lilangeni",
             "Thai Baht",
             "Tajikistani Somoni",
             "Turkmenistan Manat",
             "Tunisian Dinar",
             "Tongan Paʻanga",
             "Turkish Lira",
             "Trinidad and Tobago Dollar",
             "Tuvaluan Dollar",
             "New Taiwan Dollar",
             "Tanzanian Shilling",
             "Ukrainian Hryvnia",
             "Ugandan Shilling",
             "United States Dollar",
             "Uruguayan Peso",
             "Uzbekistani So'm",
             "Venezuelan Bolívar Soberano",
             "Vietnamese Đồng",
             "Vanuatu Vatu",
             "Samoan Tālā",
             "Central African CFA",
             "East Caribbean Dollar",
             "Special Drawing Rights",
             "West African CFA franc",
             "CFP Franc",
             "Yemeni Rial",
             "South African Rand",
             "Zambian Kwacha",
             "Zimbabwean Dollar"
    );

    private static List<String> portugueseCoins = Arrays.asList(
            "Dirham dos Emirados Árabes Unidos",
            "Afegane afegão",
            "Lek albanês",
            "Dram Armênio",
            "Florim das Antilhas Holandesas",
            "Kwanza angolano",
            "Peso Argentino",
            "Dólar australiano",
            "Florim arubano",
            "Manat do Azerbaijão",
            "Marco da Bósnia e Herzegovina",
            "Dólar de Barbados",
            "Taka de Bangladesh",
            "Lev Búlgaro",
            "Dinar do Bahrein",
            "Franco Burundiano",
            "Dólar das Bermudas",
            "Dólar de Brunei",
            "boliviano boliviano",
            "real brasileiro",
            "Dólar das Bahamas",
            "Ngultrum butanês",
            "Pula do Botsuana",
            "Rublo Bielorrusso",
            "Dólar belizenho",
            "Dólar canadense",
            "Franco Congolês Democrático",
            "Franco suíço",
            "Peso Chileno",
            "Yuan Chinês",
            "Peso Colombiano",
            "Costa riquenho",
            "Peso cubano",
            "cabo verdiana",
            "Coroa Tcheca",
            "Franco Djibutiano",
            "Coroa Dinamarquesa",
            "Peso Dominicano",
            "Dinar Argelino",
            "Libra egípcia",
            "Nakfa da Eritreia",
            "Birr etíope",
            "Euro da União Europeia",
            "Dólar de Fiji",
            "Libra das Ilhas Malvinas",
            "Coroa faroense",
            "Libra esterlina do Reino Unido",
            "Lari georgiano",
            "Libra de Guernsey",
            "Cedi ganês",
            "Libra de Gibraltar",
            "Dalasi gambiano",
            "Franco Guineense",
            "Quetzal da Guatemala",
            "Dólar guianense",
            "Dólar de Hong Kong",
            "Lempira hondurenha",
            "Kuna Croata",
            "Gourde haitiano",
            "Forint Húngaro",
            "Rupia Indonésia",
            "Novo shekel israelense",
            "Libra manx",
            "Rupia indiana",
            "Dinar Iraquiano",
            "Rial iraniano",
            "Coroa Islandesa",
            "Libra de Jersey",
            "Dólar jamaicano",
            "Dinar Jordaniano",
            "Iene japonês",
            "Xelim Queniano",
            "Som do Quirguistão",
            "Riel cambojano",
            "Dólar Quiribati",
            "Franco Comoriano",
            "Won sul-coreano",
            "Dinar do Kuwait",
            "Dólar das Ilhas Cayman",
            "Tenge do Cazaquistão",
            "Laos Kip",
            "Libra Libanesa",
            "Rupia do Sri Lanka",
            "Dólar da Libéria",
            "Lesoto Loti",
            "Dinar Líbio",
            "Dirham Marroquino",
            "Leu da Moldávia",
            "Ariary malgaxe",
            "Denar macedônio",
            "Kyat birmanês",
            "Tögrög da Mongólia",
            "Pataca macaense",
            "Ouguiya da Mauritânia",
            "Rupia das Maurícias",
            "Rufiyaa das Maldivas",
            "Kwacha do Malawi",
            "Peso Mexicano",
            "Ringgit malaio",
            "Metical Moçambicano",
            "Dólar da Namíbia",
            "Naira nigeriana",
            "Córdoba Nicaraguense",
            "Coroa Norueguesa",
            "Rúpia Nepalesa",
            "Dólar da Nova Zelândia",
            "Rial de Omã",
            "Balboa panamenho",
            "Sol peruano",
            "Kina da Papua Nova Guiné",
            "Peso filipino",
            "Rupia Paquistanesa",
            "Zloty polonês",
            "Guarani paraguaio",
            "Rial do Catar",
            "Leu romeno",
            "Dinar Sérvio",
            "rublo russo",
            "Franco Ruandês",
            "Rial saudita",
            "Dólar das Ilhas Salomão",
            "Rupia Seichelense",
            "Libra Sudanesa",
            "Coroa Sueca",
            "Dólar de Singapura",
            "Libra de Santa Helena",
            "Leoa da Serra Leoa",
            "Xelim Somali",
            "Dólar do Suriname",
            "Libra do Sudão do Sul",
            "São Tomé e Príncipe Dobra",
            "Libra Síria",
            "Essuatíni Lilangeni",
            "Baht tailandês",
            "Somoni tadjique",
            "Manat do Turquemenistão",
            "Dinar Tunisino",
            "Pa'anga de Tonga",
            "Lira turca",
            "Dólar de Trinidad e Tobago",
            "Dólar tuvaluano",
            "Novo dólar taiwanês",
            "Xelim da Tanzânia",
            "Hryvnia ucraniana",
            "Xelim ugandês",
            "Dólar estadunidense",
            "Peso Uruguaio",
            "Sou do Uzbequistão",
            "Bolívar Soberano venezuelano",
            "Dong vietnamita",
            "Vatu de Vanuatu",
            "Tala Samoana",
            "CFA da África Central",
            "Dólar do Caribe Oriental",
            "Direitos de Saque Especiais",
            "Franco CFA da África Ocidental",
            "Franco CFP",
            "Rial Iemenita",
            "Rand sul-africano",
            "Kwacha da Zâmbia",
            "Dólar do Zimbábue"
    );

    static String [] country = {
            "United Arab Emirates",
            "Afghanistan",
            "Albania",
            "Armenia",
            "Netherlands Antilles",
            "Angola",
            "Argentina",
            "Australia",
            "Aruba",
            "Azerbaijan",
            "Bosnia and Herzegovina",
            "Barbados",
            "Bangladesh",
            "Bulgaria",
            "Bahrain",
            "Burundi",
            "Bermuda",
            "Brunei",
            "Bolivia",
            "Brazil",
            "Bahamas",
            "Bhutan",
            "Botswana",
            "Belarus",
            "Belize",
            "Canada",
            "Democratic Republic of the Congo",
            "Switzerland",
            "Chile",
            "China",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Cape Verde",
            "Czech Republic",
            "Djibouti",
            "Denmark",
            "Dominican Republic",
            "Algeria",
            "Egypt",
            "Eritrea",
            "Ethiopia",
            "European Union",
            "Fiji",
            "Falkland Islands",
            "Faroe Islands",
            "United Kingdom",
            "Georgia",
            "Guernsey",
            "Ghana",
            "Gibraltar",
            "The Gambia",
            "Guinea",
            "Guatemala",
            "Guyana",
            "Hong Kong",
            "Honduras",
            "Croatia",
            "Haiti",
            "Hungary",
            "Indonesia",
            "Israel",
            "Isle of Man",
            "India",
            "Iraq",
            "Iran",
            "Iceland",
            "Jersey",
            "Jamaica",
            "Jordan",
            "Japan",
            "Kenya",
            "Kyrgyzstan",
            "Cambodia",
            "Kiribati",
            "Comoros",
            "South Korea",
            "Kuwait",
            "Cayman Islands",
            "Kazakhstan",
            "Laos",
            "Lebanon",
            "Sri Lanka",
            "Liberia",
            "Lesotho",
            "Libya",
            "Morocco",
            "Moldova",
            "Madagascar",
            "North Macedonia",
            "Myanmar",
            "Mongolia",
            "Macau",
            "Mauritania",
            "Mauritius",
            "Maldives",
            "Malawi",
            "Mexico",
            "Malaysia",
            "Mozambique",
            "Namibia",
            "Nigeria",
            "Nicaragua",
            "Norway",
            "Nepal",
            "New Zealand",
            "Oman",
            "Panama",
            "Peru",
            "Papua New Guinea",
            "Philippines",
            "Pakistan",
            "Poland",
            "Paraguay",
            "Qatar",
            "Romania",
            "Serbia",
            "Russia",
            "Rwanda",
            "Saudi Arabia",
            "Solomon Islands",
            "Seychelles",
            "Sudan",
            "Sweden",
            "Singapore",
            "Saint Helena",
            "Sierra Leone",
            "Somalia",
            "Suriname",
            "South Sudan",
            "São Tomé and Príncipe",
            "Syria",
            "Eswatini",
            "Thailand",
            "Tajikistan",
            "Turkmenistan",
            "Tunisia",
            "Tonga",
            "Turkey",
            "Trinidad and Tobago",
            "Tuvalu",
            "Taiwan",
            "Tanzania",
            "Ukraine",
            "Uganda",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Venezuela",
            "Vietnam",
            "Vanuatu",
            "Samoa",
            "CEMAC",
            "Organisation of Eastern Caribbean States",
            "International Monetary Fund",
            "CFA",
            "Collectivités d'Outre-Mer",
            "Yemen",
            "South Africa",
            "Zambia",
            "Zimbabwe",
    };
}
